* Conscious Eating

Awareness, Knowledge and 

** A fat chat

Carbohydrate gets converted to fats, but they need to be converted to ketones before getting back to carbs. Fats can't be converted back into carbs.

*** the myth: 
    Fats == bad == unhealthy
*** The fact:  
    Too many refined carbs with nowhere to go. 
    Body wants to work hard to get energy out of food. 
    With refined carbs it doesn't have to. Refined carbs gets stored as fat. In the refining process you lose the fibre.

*** Body fat functions

**** Energy storage
 Use carbs for energy and stores rest as fat

**** Sequesters / stores toxins
Keeps body safe against bad stuff

**** Insulation and protection
Fat under skin keeps you warm and unsulated

*** Fats you want in your diet

Avocado oil, omega 3, nuts, seeds, chia seeds, olive oil, non plant oils

Omega 3 helps with depression

Fats help us to moderate the stressful effects of modern living.

*** Relationship with fats

**** Weight Loss
 What determines a body weight? Body type, and how do you engage that body type. How does your body store fat genetically.

 What causes weight gain?
 - Consuming in excess
 - Hormonal imbalances
 - Different illnesses that store extra fat
 - emotional eating
 - sedentary lifestyle

Weight is a very poor representation of health. 

Health is not what your body looks like, it's also mental health. 

We have a very fat phobic and fat shaming culture.

Different cultures carry different body types because that's how they've gotten over years of evolution. 

Our measurement of health is how thin are you, and this is a myth and is destructive

It's easier to feel good about yourself when you're thin because you like to see yourself through other's eyes and they treat you better if you're thin

There is a level of fat that is harmful - obesity increases risk of heart disease and stuff

***** Overeating
Not as simple as I put too much food in my mouth.
 There are emotional underlying triggers:
 - boredom: The inability to sit still. We live in a world where we're constantly stimulated. We don't really ever stop. Our grandparents will just sit there for 2 hours and stare... we can't do that.

We've also started categorising emotions as good and bad. When we sit still all these emotions you've been taught to supress will come back to you. 
Thus we avoid them and find something to do. Coping mechanism that circumvents the necessity for dealing with those issues. We're demonising our emotions.

 - shame / guilt
A sense of inadequacy - you are not enough, you are not worthy
Carrying other people's emotional burdens is not good
Our culture is hinged on shame and guilt


'We are comforted by food' - eating is a very grounding activity; convenience food is often addictive

Food can act to insulate us against challenging emotions

*** Weight gain

Imabalance of function.

*** Weight loss

Side effect of the improved efficiency of your vessel
If you are carrying additional weight that is unhealthy for you, weight loss will be a side effect of working towards improving your health


It is important to determine which of your desires and goals are yours, and which come from external expectations and pressures

** What is obese?

When your mobility is impeded, insulin resistant, cholestrol spiked. Obese people is normally malnutritioned. You start craving things that you've eaten. 
If you don't have a "database" inside you that shows what you've had and how it works, all you know is "hungry", so you keep eating a lot of carbs and protein, but not actually nourished.
You don't know that you need magnesium and this and that.


** Weight fluctuation
Check ovulation cycle - you most likely fluctuate around your fertile window


