* Defining Data Science

** Define terms

*** Analysis

Perform analysis on data that happened in the past. Do analysis to explain how and why something happened

*** Analytics

Explores potential future events
 
 - Qualitative = using intuition + analysis for analytics
 - Quantative = using formulas and algorithms for analytics

*** Business Intelligence

The process of analysing and reporting historical business data

Typical job titles in BI: 
 - BI Analyst [ Performs analyses and reporting of past historical data ]
 - BI Consultant [ "External BI analyst" ]
 - BI Developer [ More advanced analyses specifically designed for the company using tools like SQL and Python ]

*** Big Data vs Traditional Data

Traditional data is data you can manage as a human

Big Data is classified according the 3 V's:
  - Volume [ A LOT of data, more than a human can manage without tools ]
  - Variety [ Audio, Video, Text (structured and unstructured) .. ]
  - Velocity [ Speed of data, e.g. recording stock prices once per second ]

*** AI

Simulating human knowledge and decision making with computers

**** Machine learning

The ability of machines to predict outcomes without being explicitly programmed.

ML is about creating and implementing algorithms that let machines receive data and use this data to:
 - make predictions
 - analyse patterns
 - give predictions


** Data science disciplines

Analytics is used in modern days to describe roles that technically do analytics + analysis e.g. business analytics / data analytics

-- see confusing diagram in Part 1 S2_L6: https://www.dropbox.com/home/The%20Data%20Science%20Course%202020%20-%20All%20Resources/Part_1_Intro_to_Data_and_Data_Science/S2_L6

-- cute infografic part 1 S2_L7: https://www.dropbox.com/home/The%20Data%20Science%20Course%202020%20-%20All%20Resources/Part_1_Intro_to_Data_and_Data_Science/S2_L7?preview=365-DataScience.png


* Probabilities

Quantifying how likely each event is on it's own

Probability noted as numbers between 0 and 1, 0 = event definitely not ocurring, 1 definitely ocurring

** Definition

A -> event
P(A) -> probability

P(A) = preferred (favourable) / all (sample)

E.g. coin flip, where you want heads: P(A) = 1 / 2 (1 preferred outcome)
     rolling a 1d6 - where your preferred outcome is 1, total = 6, thus 1/6
                   - where your preferred outcome is divisable by 3, thus preferred = 2 = 2/6

Probability of 2 ovents is the same as the product of the product of these events separately

P(A and B) = P(A).P(B)

** Experimental probabilities

Do an amount of trials to have an experiment. E.g. toss a coin 20 times - 20 trials = 1 experiment.
The resulting probabilities = experimental vs theoretical

P(A) = successful trials / all trials

Expected outcome E(A) used to predict future events

*** Categorical outcomes

To get the expected outcome of drawing a spade from a deck of cards, multiply the theoretical probability (13 / 52 = 0.25) with the amount of tries (n).
 Thus, for an experiment with 20 tries, we're expecting to get a spade 5 times during the experiment.

*** Numerical outcomes

Take the value for every element in the sample space, multiple with its probability and add them together

E(x) = P(A).A + P(B).B + P(C).C

** Probability frequence distribution

A Collection of the probabilities for each possible outcomes

Create a table with the value and the frequency of how often they can appear. Divide this number by the sample space = frequency distibution

Can use a table or a graph to show this.

E.g. dice rolls, to roll a number using 2d6 means you have 36 possible outcomes

Table of sums of dice:

   1 2 3 4  5  6

1  2 3 4 5  6  7 
2  3 4 5 6  7  8 
3  4 5 6 7  8  9
4  5 6 7 8  9  10
5  6 7 8 9  10 11
6  7 8 9 10 11 12

This shows that every diagonal line is duplicated. Thus you have a 6 / 36 = 1 / 6 chance to roll a 7, vs 1 / 36 chance to roll a 2.

The frequency distribution table would look like this, start with the list of all values + number of times they feature, then showing their probability

Val # probability
2   1 1/36
3   2 1/18
4   3 1/12
5   4 1/9
6   5 5/36
7   6 1/6
8   5 5/36
9   4 1/9
10  3 1/12
11  2 1/18
12  1 1/36

If you represent this as a graph, you can see that your interval should probably be 6 - 8

** Events and their Complements

A complement of an event, is everything an event is not

Adding all probabilities should always add up to 1 = certainty

Sum of probabilities > 1 : we counted stuff more than once
Sum of probabilities < 1 : we missed a section of the sample space

Event A
Complement A'

P(A) + P(B) + P(C) = 1
A' = B + C
P(A') = 1 - P(A)

E.g. rolling a 1,2,4,5 or 6 on a dice
P(A) = 1/6 * 5 = 5/6

rolling a 3: P(A') = 1/6

P(A) + P(A') = 1

